### ISSUE TITLE
Training efficiency problem

### ISSUE THREAD

**Issue by JetRunner** [malyasova/pytorch_vq_vae_audio#1]
Hi @malyasova,
I found your project very interesting and educational. Thanks for sharing!
However, I've tried your notebook on VCTK and it seems to be running extremely slow (I use an Nvidia P100). Is it normal? 

Also, could you kindly share your pre-trained checkpoint?

**Comment by malyasova** [comment]
Dear JetRunner,
It would not be of much use to you since I could never get the model to produce coherent speech; I believe there is some bug in my implementation. I could never find it and gave up.

**Comment by JetRunner** [comment]
😉 no problem! Thanks for your reply any way.
